version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "8080:80"
    container_name: chatbot-frontend
    restart: unless-stopped
    
  # Future backend service (when you create your FastAPI backend)
  # backend:
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  #   container_name: chatbot-backend
  #   restart: unless-stopped
  #   environment:
  #     - DATABASE_URL=postgresql://user:password@db:5432/chatbot
  #   depends_on:
  #     - db
  
  # Future database service
  # db:
  #   image: postgres:15-alpine
  #   container_name: chatbot-db
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: chatbot
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
