name: Simple CI

# Trigger on push and pull requests
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      continue-on-error: true  # Don't fail the build on lint errors for now
      
    - name: Build application
      run: npm run build
      
    - name: Test Docker build
      run: |
        docker build -t chatbot-test .
        echo "Docker build successful!"
        
    - name: Clean up
      run: docker rmi chatbot-test
